services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-jdownloader
    cap_add:
      - NET_ADMIN
    ports:
      - 5800:5800  # porta WebUI JDownloader (VNC/NoVNC)
      - 8889:8888  # Gluetun control
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=${NORDVPN_COUNTRY:-United States}
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=5800
      - FIREWALL_INPUT_PORTS=8889
      - DOT=on
      - DOT_PROVIDERS=cloudflare

      # Health check
      - HEALTH_VPN_DURATION_INITIAL=30s
      - HEALTH_SUCCESS_WAIT_DURATION=5s

      # Timezone
      - TZ=${TZ}
    volumes:
      - /DATA/docker/jd-config/gluetun:/gluetun
    networks:
      jdownloader-network
    restart: unless-stopped

  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    network_mode: "service:gluetun"  # traffico VPN
    volumes:
      - /DATA/docker/jd-config/jdownloader:/opt/JDownloader/cfg
      - /DATA/docker/jd-downloads:/downloads
    restart: unless-stopped


networks:
  jdownloader-network:
    driver: bridge